### PR TITLE
update README: add LFX Insights badge

### PR DESCRIPTION
**Pull request by naskio**
add LFX Insights badge with link to dashboard
https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=armada

### CODE REVIEW

**Review by stackedsax — APPROVED** [review]
👍 lgtm

**Comment by naskio** [comment]
Hi @Sharpz7 
Do you have few minutes to take a look at this one?
Thanks

**Review by richscott — APPROVED** [review]

**Comment by richscott** [comment]
@naskio Can you rebase this branch from `master`, then we can re-approve and merge this? Thanks.

**Comment by naskio** [comment]
@richscott done !

**Pull request merged**
