### PR TITLE
Move website from gh-pages branch to master branch under website/ folder

### LINKED ISSUE #3715: CI: Automatic deploy of GitHub Pages doesn't work due to required protection on branches
**Describe the bug**

The CI [Deploy GH Pages](https://github.com/armadaproject/armada/actions/workflows/pages.yml) with it's current design is failing to push the latest changes from `master` to `gh-pages` due to protection over `gh-pages` branch which is in place

**Files Or Markdown that can reproduce the issue**

Reproduced: https://github.com/armadaproject/armada/actions/runs/9592573160

**Expected behavior**

When [Deploy GH Pages](https://github.com/armadaproject/armada/actions/workflows/pages.yml) workflow is triggered it should successfully publish changes to `gh-pages` branch which will then trigger the [pages-build-deployment](https://github.com/armadaproject/armada/actions/workflows/pages/pages-build-deployment) workflow and publish new content

**Actual behavior**

Current push to `gh-pages` is not working due to protected `gh-pages` branch

**Additional context**

##### Steps to perform manual deploy from local machine
 - checkout `master` branch in `master` folder
 - checkout `gh-pages` branch in `gh-pages` folder
 - Follow steps below:
```bash
# Move files to `gh-pages` branch
cp master/docs/*.md gh-pages/
rm gh-pages/docs-readme.md
cp -r master/docs/developer gh-pages/
cp master/CODE_OF_CONDUCT.md master/CONTRIBUTING.md gh-pages/_pages/

# Commit and push changed files to `gh-pages` branch
cd gh-pages
git checkout feature/update-gh-pagex-XXX # name of new branch
git add . _pages
git commit -m "Updating Github Pages branch with latest Master changes"
git push origin feature/update-gh-pagex-XXX
```
- Open a PR to merge `feature/update-gh-pagex-XXX` -> `gh-pages`
- Once PR is merged the [pages-build-deployment](https://github.com/armadaproject/armada/actions/workflows/pages/pages-build-deployment) workflow will re-deploy new content to [armadaproject.io](https://armadaproject.io/)

Possible solutions:
- Instead of pushing changes to `gh-pages` directly we can edit current workflow to open a PR to `gh-pages` which is valid way to respect security and still contribute to the branch
- TBD

### PR DESCRIPTION
**Pull request by naskio**
### What type of PR is this?

Enhancement of website build and deployment process.

#### Current solution:

Armada's website is a static site built with Jekyll and hosted on GitHub Pages. Currently:

- It's source code resides in the `gh-pages` branch.
- Documentation is written in Markdown format and stored in the `docs/` folder within the `master` branch.
- The workflow `Deploy GH Pages`, located at `.github/workflows/pages.yml` within the `master` branch, is responsible
  for copying the documentation files from the `master` branch to the `gh-pages` branch.
- We use the `Deploy from a branch` option as source for building and deploying the website to GitHub Pages.
- The build and deployment process is triggered by pushing changes to the `gh-pages` branch, either through a pull
  request or through the `Deploy GH Pages` workflow.
- The website is accessible at https://armadaproject.io.

#### Issues with the current solution:

- Having a separate branch `gh-pages` for the website source code increases complexity and maintenance overhead.
- Keeping documentation in sync between the `master` and `gh-pages` branches requires additional effort and can lead to
  inconsistencies.
- A few weeks ago, protection rules were added to the `gh-pages` branch to prevent direct pushes. As a result,
  the `Deploy GH Pages` workflow can no longer push changes to the `gh-pages` branch. The only way to update
  the website now is through a pull request.

#### Proposed Solution:

To address the issues mentioned above, we propose the following setup:

- **Relocate Source Code:** Move the website source code from the `gh-pages` branch to the `master` branch under
  a `website/` folder.
- **Centralize Documentation:** Keep all documentation in Markdown format within the `docs/` folder in the `master`
  branch, using it as the source for the website content.
- **Automate with GitHub Actions:** Use GitHub Actions to build and deploy the website directly from the `master`
  branch.

This setup will simplify the build and deployment process, making it easier to maintain and update the website. It will
also ensure that the documentation is always in sync with the website content and is accessible from the IDE, GitHub,
and the website.

> [!NOTE]
> More efforts have been made to ensure that the website works correctly on forks to allow previewing changes. my PR is available for preview at [https://naskio.github.io/armada/](https://naskio.github.io/armada/).

### Which issue(s) this PR fixes:

Fixes #3715

### Special notes for your reviewer:

Once this PR is merged, we would also need to:

- [ ] Set "Source" to "GitHub Actions" in "Settings > Pages > Build and deployment > Source".
- [ ] Set "Custom domain" to `armadaproject.io` in "Settings > Pages > Build and deployment > Custom domain".
- [ ] Get rid of the `gh-pages` branch (Optional).

There's also few more minor issues that need to be addressed:

- [ ] The file `docs/developer/etc-localdev.md` doesn't exist, but it's referenced in `docs/developer/README.md`.
- [ ] The file `docs/quickstart/img/lookout.png` doesn't exist, but it's referenced in `docs/demo.md`.
- [ ] At the `website/index.html` we refer to `/user#queue`, `/user#job` and `/user#job-set` but these sections don't
  exist.

### CODE REVIEW

**Review by Sharpz7 — CHANGES_REQUESTED** [review]
Hey @naskio, thanks for working on this.

I would be hesitant to move to this solution because of the requirement that the website would have to be built locally every time you want to make a change to a README and have it reflected on the website (Unless I am mistake, this is the reason for the way it was originally)

We would either need to enforce CI to check that the website is built to latest (a process we already do for the auto-generated https://github.com/armadaproject/armada/blob/master/docs/python_armada_client.md in the python client), or just let the website get stale without pushes. 

If more work can be done, maybe a Github Action that builds the website and opens a PR automatically? Is that possible?

I apologize if I am missing something - I am definitely in support of removing the current system if we can address this problem / agree it is okay.

**Comment by naskio** [comment]
Hi @Sharpz7,

The website will be built by the workflow `.github/workflows/deploy-website.yml`. 
To update the documentation, you need to:
1. Make changes to files in the `docs/` folder
2. Once your changes are merged into the main branch, the workflow will automatically:
   - Build a new version of the website
   - Publish it to GitHub Pages

You don't really need to build the website locally unless you want to develop something related to the website.

This approach is preferable to using a `gh-pages` branch as it eliminates potential duplication issues and keeps everything in the main branch.

**Comment by Sharpz7** [comment]
Hey @naskio 

Most of this change is made up of website-based files (HTML Files, CSS Files etc). They can be removed from this change if it is being built in CI?

That is more what I was thinking about when I wrote my original comment.

**Comment by naskio** [comment]
@Sharpz7 
Actually, the website has Jekyll source files (Markdown, HTML templates, CSS, JS) which are different from the output (static files).
The CI will take the Jekyll website source (Markdown content, HTML templates, CSS and JS sources) and generate the static website (rendered HTML, CSS and JS) and publish them to GitHub Pages.

**Review by Sharpz7 — APPROVED** [review]
@naskio ah okay - it doesn't look like files we should need in the main repo (a lot of them do not look like source, they look like things that have been downloaded from other places), but I trust your judgement, since you have been leading these efforts.

Thank you, and thanks for answering my questions :))

**Pull request closed without merging**
