### PR TITLE
Feat/responsive logs modal

### PR DESCRIPTION
**Pull request by Ginohmk**
Fixes #

#### Special notes for your reviewer:
- New tab view for logs: is implemented using Redux persist, in other to persist the log details in a new browser tab. Please run `yarn install` before starting the UI server, so as t install new dependencies. 

#### Old view of Job Log
image

#### Video of interface and New feature shown below.
https://github.com/armadaproject/armada/assets/58771507/f60d1f69-175b-471e-afdc-69757715aa09

##### Lookout V2 video (Showing the new Window tab feature implemented) and UI tweaks.

https://github.com/armadaproject/armada/assets/58771507/ad1d1c75-5bce-48e8-8091-c60abe470dcb

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-590) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Ginohmk** [comment]
@richscott  The changes (Two files added to .gitignore) has being removed
-  the developer/env/binoculars.env and developer/env/lookout.env has been reverted to its default localhost.

**Comment by samclark** [comment]
Hello 👋 Thanks for raising this PR and for taking the time to create some demo videos. From the video it seems the V2 log window no longer has drop down lists to allow you to choose the `job run` or `container`... have these been removed by mistake? One other nit is that it looks like the `Job Logs View` header takes up a lot of space. I would be in favor removing it to get more screen space or alternatively replacing it with the job id, job run date, and container name details in a much smaller text size would be even better.

**Comment by Ginohmk** [comment]
Thanks for your feedback @samclark , I will effect the changes as you have stated and update this PR.

**Review by richscott — APPROVED** [review]

**Comment by richscott** [comment]
The changes in this PR were merged in via a separate PR a couple months ago - now closing this.

**Pull request closed without merging**
