### PR TITLE
Feature/update webpack

### PR DESCRIPTION
**Pull request by Ginohmk**
Fixes #

#### Special notes for your reviewer:

I could not find the issue relating to this task on the project issues.hence why i do not have an issue link to the PR.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-430) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by richscott — COMMENTED** [review]
Hi, Kanu. The most immediate thing I see that I think will need changing is that I don't believe all those files in `.yarn/....` need to be included in the PR - shouldn't all that be dynamically re-created whenever a build is done? Prior to this PR, there is no `internal/lookout/ui/.yarn/` in the repo at all. 

Also, to ensure this doesn't accidentally happen again, maybe add an entry into the top-level `.gitignore` file (at the top of the Armada repo), in the `#Yarn` section, a line like:
```
.yarn/
```
and then verify Git ignores any existing one by doing `git status`, etc.

Can you try removing those from the branch, and re-running the build & tests? It should still be successful.

**Comment by Ginohmk** [comment]
@richscott The extra files has being ignored (added to .gitignored).

**Review by kannon92 — DISMISSED** [review]

**Review by Sharpz7 — DISMISSED** [review]

**Comment by Sharpz7** [comment]
I want to see at least one more approval before merging.

**Review by richscott — DISMISSED** [review]

**Comment by richscott** [comment]
The changes in this PR were merged in via a separate PR a couple months ago - now closing this.

**Pull request closed without merging**
