### PR TITLE
Added poll_interval in Deferrable operator

### LINKED ISSUE #2473: Deferrable operator should also have poll_interval
We added poll_interval to our armadaOperator.  https://github.com/armadaproject/armada/pull/2444

I noticed that we didn't add this API field to the deferrable operator.  We should add poll_interval as a parameter (https://github.com/armadaproject/armada/blob/master/third_party/airflow/armada/operators/armada_deferrable.py#L83)

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-286) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by Nawaz027**
Fixes #2473 

Fixes #2473

#### Special notes for your reviewer:

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-294) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by kannon92** [comment]
Thanks for this! I think you will get some failures because of docs.  You may need to generate the documentation via tox.

**Comment by Nawaz027** [comment]
Hey @kannon92 I did the suggested changes. Please do have a look and share your feedback.

**Comment by kannon92** [comment]
Will you get a chance to look into the doc issue?  

You can reproduce the CI failures by running the `tox -e docs-check` and see why it is telling you.  I can't really see why it is failing but it looks like the check is detecting differences in whitespace.

**Comment by Nawaz027** [comment]
Okay. Just looking into it.

**Comment by kannon92** [comment]
@Nawaz027 Are you still working on this PR?

**Pull request closed without merging**
