### PR TITLE
Removed Makefile from repo

### PR DESCRIPTION
**Pull request by MeenuyD**
issue: #2899 
Removed the makefile from the repository and other files where it was mentioned.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-700) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Mo-Fatah** [comment]
Thanks for your contributions! This issue seems to be already taken and someone has already filed a PR before #2913 . You can still pick a "good first issue" ticket and starting hacking on it. We look forward to your first contribution with us!

**Comment by MeenuyD** [comment]
Hello, @Sharpz7 I checked the command I did not find it I deleted the command which has makerfile.

**Comment by Sharpz7** [comment]
Cool! We need to wait for a few more approvals and then we can merge :))

**Comment by MeenuyD** [comment]
ok Thanks

**Comment by Sharpz7** [comment]
There are a few more small references. See 

https://github.com/search?q=repo%3Aarmadaproject%2Farmada+%22make+%22+AND+%28NOT+%28language%3AGo+OR+%22%23+Make+%22%29%29&type=code

**Comment by MeenuyD** [comment]
Do we have to delete all which are starting with make?

**Comment by Sharpz7** [comment]
@MeenuyD No, but take for example:

https://photos.app.goo.gl/4FeFjNgpnEq11DRW6
https://photos.app.goo.gl/11HW59nnZzxBUbJg8

These reference `make` commands which now have a `mage` equivalent. They might not have the same name, so check the `magefiles` folder, and try and find the best equivalent.

**Comment by MeenuyD** [comment]
Hello, @Sharpz7 What I understand I have to check for the make command inside the magefiles folder.

**Comment by Sharpz7** [comment]
@MeenuyD not quite. Mage and make are two different technologies. We are switching from make to mage. Most of the changes are done, I just need these few last things changed to complete the move :))

**Comment by MeenuyD** [comment]
Ok, I am trying.

**Review by Mo-Fatah — APPROVED** [review]

**Comment by Mo-Fatah** [comment]
@MeenuyD  Can you sign off your commit to pass the DCO check ?
Since this a single commit, if you have your username and email configured in git, you can use `git commit --amend --signoff` then push the changes.
see : https://volunteer.coscup.org/docs/en/dev/how-to-signoff/

**Pull request merged**
