### PR TITLE
Seperate python script for armada v1 and v2 system diagrams

### LINKED ISSUE #2738: Armada V1 and Armada V2 diagrams
Armada is migrating to a new set of components. To help users with that move, we need to have diagrams of both setups.

Currently we have https://github.com/armadaproject/armada/blob/master/docs/design/diagrams/relationships/armada_system.png, which is **created using code** from here https://github.com/armadaproject/armada/blob/master/docs/design/diagrams/relationships/generate.py. The one change that needs to happen, is it should be called "Lookout V2" instead of just "Lookout".

For the Lookout V1 Doc, it should instead look like this: https://drive.google.com/uc?id=1XtXdCP2dVXa2pXqLFGHdeSNkh8A6hBt8. Where items crossed out are part of V2, and the items in the green box are all one component.

We should have https://github.com/armadaproject/armada/blob/master/docs/design/relationships_diagram.md be changed to include both diagrams. I expect a PR for this to be a back-and-forth process.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-524) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by Pradeep-Kurapati**
#### What this PR does:
This pull request gives the seperate diagram for Armada V1 System.

#### Issue PR fixes:

Fixes #2738 

#### Special notes for your reviewer:
1. Please check if the diagram is correct. 
2. Should we remove `generate.py` as I'm thinking of `generate_v1.py` and `generate_v2.py`?
3. If this diagram is correct, I will be commiting generate_v2.py

Here is the resultant diagram:

image

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-544) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Sharpz7** [comment]
Great start! A few things:

Armada V1 actually uses lookout V2, but in a special way. The pulsar -> Lookout V2 Ingester -> Lookout V2 API loop exists, but instead, it also talks to the Lookout V1 UI. can you add that in?

Also, Pulsar does not talk to the executors, instead, the executors talk to Armada Server (This way, Armada Server is not responsible for keeping track of its executors, the executors need to send data to the server, and it responds with a decision). Also, if you are able to add in the Armada Clients talking to The server like in the V2 Doc that would be great.

**Comment by Pradeep-Kurapati** [comment]
This looks very wrong. Please review this. Thank you:

image

**Comment by Sharpz7** [comment]
Yeah so this needs a few more things:

- The lookout V2 API talks to The Lookout V1 UI. 
- Pulsar does not talk to the lookout V1 UI.
- The Executor API does not talk to the Redis Scheduler, in fact, remove the redis scheduler, as for V1 it is included inside the Armada Server. I.e make all connections going to the Redis scheduler go to the server instead
- https://drive.google.com/uc?id=1eeaX7EMdJfCXBgVKcNkiHV9yG1zqxBqO These components need to be duplicated for the V1 Lookout. There should, be two of these, with the Lookout V1 and V2 APIs being the only components which talk to the Lookout UI

**Comment by Pradeep-Kurapati** [comment]
I did not clearly understand the last point. When you said V1 Lookout, were you referring to Lookout V1 UI or is it a component I didn't add? Some clarification about the last point would be great!

image

**Comment by Pradeep-Kurapati** [comment]
@Sharpz7, please review Armada V2 System diagram also: 

image

**Comment by Pradeep-Kurapati** [comment]
@Sharpz7 kindly review the changes and provide feedback. Thank you.

**Comment by Sharpz7** [comment]
V2 is looking good now!

V1 Needs this change https://drive.google.com/uc?id=1cBMG1pR6c5KUGAwRqvLA03tbmQMHZyEM. You need to add a 2nd ingester and API in for lookout V1 and connect it as shown.

**Comment by Pradeep-Kurapati** [comment]
@Sharpz7 Please review V1 diagram:

image

**Comment by Pradeep-Kurapati** [comment]
Roger that!

**Comment by Pradeep-Kurapati** [comment]
I updated relationships_diagram.md to include our new diagrams. Please suggest necessary reviews. Thanks!

**Comment by Pradeep-Kurapati** [comment]
@Sharpz7 @kannon92 Hi there! I just wanted to check in on the status of this pull request. Would appreciate any feedback or suggestions. Thank you!

**Comment by Pradeep-Kurapati** [comment]
@Sharpz7 @kannon92 Hi there! I just wanted to check in on the status of this pull request. Would appreciate any feedback or suggestions. Thank you!

**Comment by Sharpz7** [comment]
Apolgies for not getting back to you, will look at this today.

**Review by Sharpz7 — APPROVED** [review]
I am happy for no more time to be spent on this. I think the diagrams do a good enough job.

**Review by richscott — APPROVED** [review]

**Pull request merged**
