### PR TITLE
Added test file for cmd/armadactl/cmd/cancel_test.go

### PR DESCRIPTION
**Pull request by biswajit-9776**
Fixes #
Issue #2167 
#### Special notes for your reviewer:

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-221) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by kannon92 — COMMENTED** [review]
Thank you for your PR.  Can you get the lint issues fixed and then I’ll review?

**Comment by biswajit-9776** [comment]
I have updated the file by running golangci-lint run --fix on the file. I hope it's ready for your review.

**Review by kannon92 — CHANGES_REQUESTED** [review]
Can you make sure your PR only has your additions?

**Comment by biswajit-9776** [comment]
I apologise for the inconvenience. The other account is not mine so I won't be able to remove its commits from this PR. Is it okay if I create another PR for this test file and close this one?

**Pull request closed without merging**
