### PR TITLE
CI: add slack alerts

### PR DESCRIPTION
**Pull request by Mo-Fatah**
I wrote a custom [action](https://github.com/Mo-Fatah/ci-alerts) to suite our needs regarding slack alerts. The current action with the current setup will send alerts to the specified slack channel only when:
- a workflow fails on `master` upstream. This will mention the whole team in the alert
- a workflow fails on a `pull_request`. this will mention the PR author on slack if their id is provided in `.github/gh-to-slackid` file. otherwise, no alert will be sent.

the alert when something fails on master/main upstream:
Screenshot from 2023-06-22 21-59-03

the alert when a PR workflow fails with a provided user's slack id:
Screenshot from 2023-06-22 22-01-10

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-376) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by kannon92 — DISMISSED** [review]

**Comment by Mo-Fatah** [comment]
@kannon92 can you have a look at this ? especially the `gh-to-slackid` file that I added. I tried to figure out another way to mention on slack but apparently this is the only way.

**Review by kannon92 — DISMISSED** [review]

**Review by richscott — COMMENTED** [review]
I really like what this does, but two things come to mind:
- this uses your `ci-alerts` GH Actions plug-in, which is cool, but that plug-in repo has (currently) no README/description, and most importantly, no LICENSE - this might cause some anxiety for the audience users. Can a basic README and an appropriate LICENSE be added for the `ci-alerts` repo, since this PR depends on that?
- would the GH-account -> Slack ID mapping file be considered a possible security leak/risk?

**Comment by Mo-Fatah** [comment]
> * this uses your `ci-alerts` GH Actions plug-in, which is cool, but that plug-in repo has (currently) no README/description, and most importantly, no LICENSE - this might cause some anxiety for the audience users. Can a basic README and an appropriate LICENSE be added for the `ci-alerts` repo, since this PR depends on that?

The action already has MIT LICENSE. 
I just added a README for the action : https://github.com/Mo-Fatah/ci-alerts/tree/main


> * would the GH-account -> Slack ID mapping file be considered a possible security leak/risk?

According to Slack API [docs](https://api.slack.com/authentication/best-practices#client-id): 

>Your Client ID is one piece of information used to identify your application and frequently appears in OAuth negotiation URLs and other contexts. Your Client ID can be shared freely in code and email and cannot be used alone to act on your application's behalf.

**Review by richscott — DISMISSED** [review]

**Comment by Mo-Fatah** [comment]
@richscott @kannon92 I just updated the triggering workflows with our new CI

**Review by kannon92 — APPROVED** [review]

**Pull request merged**
